//Author:	Nicholas Higa, Michael DiFranco
//Date:		4/9/2015(NH), 4/12/2015(NH), 4/22/2015(MD)

#pragma once

enum class CharacterState
{
	IDLE,
	SELECTED,
	MOVEMENT_SELECTED,
	MOVING,
	ATTACK_SELECTED,
	ATTACKING,
	ATTACK_CONFIRMATION,
	DEFEND_SELECTED,
	DEFENDING,
	SPEC_ATK_SELECTED,
	SPEC_ATK_CONFIRMATION
};